Add timeline of dummy
gaiax/ginstagram_rails pull request #10
Opened 2018-05-30 05:47 UTC by Ohnao

2018-05-30 06:29 UTC, ichigotake requested changes

2018-05-30 06:29 UTC, ichigotake commented on db/seeds.rb
> +5.times do |n|
おそらくこれは本番環境で実行されては困るものだと思うので、開発環境でのみ実行するとよさそうです

```
if Rails.env == 'development'
  5.times do |n|
    ...
  end
  10.times do |n|
    ...
  end
  10.times do |n|
    ...
  end
end
```

2018-05-30 07:58 UTC, ichigotake commented
>タイムラインにリダイレクトするテストですが、時間の都合で一旦切り上げています

テストは実行してませんが、レッドのまま放置しておくのはよくないです。

rspec の `pending` で保留中であることを示しつつ、コメントで保留する理由を書き記しておくと後で対応しやすくなりそうです。

2018-05-31 06:26 UTC, Ohnao commented on db/seeds.rb
> +5.times do |n|
修正完了しました！ご指摘ありがとうございます！

2018-05-31 06:29 UTC, Ohnao commented
> テストは実行してませんが、レッドのまま放置しておくのはよくないです。
> rspec の pending で保留中であることを示しつつ、コメントで保留する理由を書き記しておくと後で対応しやすくなりそうです。
そうですね！今回の場合はテスト自体を削除したので、その旨を書き記しておくと対応しやすくなりそうだと思いました。
ご指摘ありがとうございます。

2018-05-31 06:29 UTC, merged

2018-05-31 06:44 UTC, ichigotake commented on db/seeds.rb
> +5.times do |n|
`Rails.env.development?` というメソッドがあることを思い出しました。
設計原則としては文字列リテラルを利用しない記述がベターですが、今回は大した問題でもないため修正の判断はお任せします。

参考： 書籍『プリンシプルオブプログラミング』 3.12 抽象（82〜86ページ）